/*
 Navicat Premium Data Transfer

 Source Server         : first
 Source Server Type    : MySQL
 Source Server Version : 50562
 Source Host           : localhost:3306
 Source Schema         : dmps

 Target Server Type    : MySQL
 Target Server Version : 50562
 File Encoding         : 65001

 Date: 07/04/2019 14:49:08
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for adplat_ct
-- ----------------------------
DROP TABLE IF EXISTS `adplat_ct`;
CREATE TABLE `adplat_ct`  (
  `adplatformproviderid` int(11) NULL DEFAULT NULL,
  `adplatct` bigint(20) NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of adplat_ct
-- ----------------------------
INSERT INTO `adplat_ct` VALUES (31, 1);
INSERT INTO `adplat_ct` VALUES (69, 23);
INSERT INTO `adplat_ct` VALUES (100000, 230);
INSERT INTO `adplat_ct` VALUES (100002, 143389);
INSERT INTO `adplat_ct` VALUES (100003, 214);
INSERT INTO `adplat_ct` VALUES (100011, 6);
INSERT INTO `adplat_ct` VALUES (13, 20387);
INSERT INTO `adplat_ct` VALUES (100016, 3992);
INSERT INTO `adplat_ct` VALUES (100017, 5);
INSERT INTO `adplat_ct` VALUES (100018, 35027);

-- ----------------------------
-- Table structure for adspace_ct
-- ----------------------------
DROP TABLE IF EXISTS `adspace_ct`;
CREATE TABLE `adspace_ct`  (
  `adspacetypename` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `adspacect` bigint(20) NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of adspace_ct
-- ----------------------------
INSERT INTO `adspace_ct` VALUES ('视频中贴片', 10360);
INSERT INTO `adspace_ct` VALUES ('banner', 57654);
INSERT INTO `adspace_ct` VALUES ('视频暂停悬浮', 18897);
INSERT INTO `adspace_ct` VALUES ('插屏', 89797);
INSERT INTO `adspace_ct` VALUES ('视频前贴片', 15324);
INSERT INTO `adspace_ct` VALUES ('原生信息流', 20425);
INSERT INTO `adspace_ct` VALUES ('原生焦点图', 14100);

-- ----------------------------
-- Table structure for appname_ct
-- ----------------------------
DROP TABLE IF EXISTS `appname_ct`;
CREATE TABLE `appname_ct`  (
  `appname` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `appct` bigint(20) NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of appname_ct
-- ----------------------------
INSERT INTO `appname_ct` VALUES ('潮派书画', 229);
INSERT INTO `appname_ct` VALUES ('快看免费小说', 114);
INSERT INTO `appname_ct` VALUES ('总裁言情小说', 7);
INSERT INTO `appname_ct` VALUES ('多牛百变方块', 2);
INSERT INTO `appname_ct` VALUES ('每日特价', 303);
INSERT INTO `appname_ct` VALUES ('耽美纯爱精选免费vip小说', 13);
INSERT INTO `appname_ct` VALUES ('热门小说排行榜', 28);
INSERT INTO `appname_ct` VALUES ('水果爆爆乐', 6);
INSERT INTO `appname_ct` VALUES ('大球吃小球大作战', 4);
INSERT INTO `appname_ct` VALUES ('免费小说书城VIP', 3);
INSERT INTO `appname_ct` VALUES ('宠物农场', 62);
INSERT INTO `appname_ct` VALUES ('其他', 73413);
INSERT INTO `appname_ct` VALUES ('一生必读的10本智慧书', 162);
INSERT INTO `appname_ct` VALUES ('快看书城小说', 2);
INSERT INTO `appname_ct` VALUES ('捕鱼达人3（天天送金币）', 4);
INSERT INTO `appname_ct` VALUES ('[更新]2013岳云鹏精品相声全集', 3);
INSERT INTO `appname_ct` VALUES ('儿童宝贝颜色屋', 1);
INSERT INTO `appname_ct` VALUES ('豆瓣超五星小说合集', 12);
INSERT INTO `appname_ct` VALUES ('搞笑图片证件制作', 1);
INSERT INTO `appname_ct` VALUES ('消灭星星', 305);
INSERT INTO `appname_ct` VALUES ('海绵宝宝填色', 1);
INSERT INTO `appname_ct` VALUES ('最强弃少', 2);
INSERT INTO `appname_ct` VALUES ('金庸全集', 4);
INSERT INTO `appname_ct` VALUES ('僵尸尖叫', 19);
INSERT INTO `appname_ct` VALUES ('0元夺宝', 18);
INSERT INTO `appname_ct` VALUES ('百家讲坛【唯一没有广告】', 5);
INSERT INTO `appname_ct` VALUES ('宝宝汉字园', 4);
INSERT INTO `appname_ct` VALUES ('会计中级职称考试', 1);
INSERT INTO `appname_ct` VALUES ('天天连连看', 1);
INSERT INTO `appname_ct` VALUES ('唐砖', 1);
INSERT INTO `appname_ct` VALUES ('宝石2048HD', 97);
INSERT INTO `appname_ct` VALUES ('总裁言情小说全本排行榜', 40);
INSERT INTO `appname_ct` VALUES ('都市言情小说', 10);
INSERT INTO `appname_ct` VALUES ('扫雷 Simply Minesweeper ™', 10);
INSERT INTO `appname_ct` VALUES ('武神风暴', 1);
INSERT INTO `appname_ct` VALUES ('免费淘小说', 97);
INSERT INTO `appname_ct` VALUES ('PopStar! Lite', 9);
INSERT INTO `appname_ct` VALUES ('◽回到明朝当王爷【火爆】+万本精品书城 完全免费！！', 1);
INSERT INTO `appname_ct` VALUES ('单口相声全集', 1);
INSERT INTO `appname_ct` VALUES ('熊出没之熊腿小手术', 3);
INSERT INTO `appname_ct` VALUES ('官途', 2);
INSERT INTO `appname_ct` VALUES ('水果消消乐', 314);
INSERT INTO `appname_ct` VALUES ('捕鱼达人3', 71);
INSERT INTO `appname_ct` VALUES ('阅读时间', 162);
INSERT INTO `appname_ct` VALUES ('追书神器', 10);
INSERT INTO `appname_ct` VALUES ('古印加祖玛', 32);
INSERT INTO `appname_ct` VALUES ('新华字典', 4);
INSERT INTO `appname_ct` VALUES ('最热有声小说', 2);
INSERT INTO `appname_ct` VALUES ('天天消水果', 8);
INSERT INTO `appname_ct` VALUES ('vip小说免费看', 13);
INSERT INTO `appname_ct` VALUES ('超级玛丽医生', 5);
INSERT INTO `appname_ct` VALUES ('如果蜗牛有爱情', 2);
INSERT INTO `appname_ct` VALUES ('360影视大全', 3182);
INSERT INTO `appname_ct` VALUES ('佣兵天下【十三部全集】+免费小说下载阅读追书神器', 3);
INSERT INTO `appname_ct` VALUES ('经典中国象棋', 2);
INSERT INTO `appname_ct` VALUES ('百本武侠集', 1);
INSERT INTO `appname_ct` VALUES ('泡泡龙', 38);
INSERT INTO `appname_ct` VALUES ('快乐职场', 3);
INSERT INTO `appname_ct` VALUES ('精排玄幻奇幻小说', 16);
INSERT INTO `appname_ct` VALUES ('猫咪耽美小说', 2);
INSERT INTO `appname_ct` VALUES ('2013最火玄幻小说', 3);
INSERT INTO `appname_ct` VALUES ('疯狂100层', 94);
INSERT INTO `appname_ct` VALUES ('消灭星星中文版', 77);
INSERT INTO `appname_ct` VALUES ('品三国', 5);
INSERT INTO `appname_ct` VALUES ('美语听读技巧', 1);
INSERT INTO `appname_ct` VALUES ('资讯-and', 810);
INSERT INTO `appname_ct` VALUES ('养生头条', 250);
INSERT INTO `appname_ct` VALUES ('内涵段子', 94);
INSERT INTO `appname_ct` VALUES ('如意头条-科大', 61);
INSERT INTO `appname_ct` VALUES ('医道官途', 2);
INSERT INTO `appname_ct` VALUES ('妹妹糖 hd 3', 7);
INSERT INTO `appname_ct` VALUES ('瘦身必读', 5);
INSERT INTO `appname_ct` VALUES ('中期报告', 1);
INSERT INTO `appname_ct` VALUES ('军事头条新闻', 1);
INSERT INTO `appname_ct` VALUES ('停车大师3D 大巴车', 39);
INSERT INTO `appname_ct` VALUES ('小米小说', 3);
INSERT INTO `appname_ct` VALUES ('水果连连看3', 182);
INSERT INTO `appname_ct` VALUES ('全本小说', 261);
INSERT INTO `appname_ct` VALUES ('麻将(单机版)', 17);
INSERT INTO `appname_ct` VALUES ('最火穿越小说', 2);
INSERT INTO `appname_ct` VALUES ('太极拳入门初步', 5);
INSERT INTO `appname_ct` VALUES ('读么', 2);
INSERT INTO `appname_ct` VALUES ('象棋学园', 2);
INSERT INTO `appname_ct` VALUES ('甜心消消乐', 1);
INSERT INTO `appname_ct` VALUES ('穿越言情小说', 147);
INSERT INTO `appname_ct` VALUES ('席绢全集', 1);
INSERT INTO `appname_ct` VALUES ('PopStar', 7);
INSERT INTO `appname_ct` VALUES ('水果消消', 30);
INSERT INTO `appname_ct` VALUES ('最新完结穿越小说', 24);
INSERT INTO `appname_ct` VALUES ('com.xunxin.majiang', 1);
INSERT INTO `appname_ct` VALUES ('失眠克星', 1);
INSERT INTO `appname_ct` VALUES ('畅销言情小说全本精选', 59);
INSERT INTO `appname_ct` VALUES ('围棋练习大全', 3);
INSERT INTO `appname_ct` VALUES ('噪声检测仪', 1);
INSERT INTO `appname_ct` VALUES ('极品钢琴', 1);
INSERT INTO `appname_ct` VALUES ('掌上书城', 56);
INSERT INTO `appname_ct` VALUES ('全本小说离线读【豪华精排免费书城】', 14);
INSERT INTO `appname_ct` VALUES ('快阅', 48);
INSERT INTO `appname_ct` VALUES ('iMusic - iOS - 320x50', 3);
INSERT INTO `appname_ct` VALUES ('连连看水果版', 4);
INSERT INTO `appname_ct` VALUES ('每日一读', 23);
INSERT INTO `appname_ct` VALUES ('2015中国法律法规大全 附免费连载小说下载', 2);
INSERT INTO `appname_ct` VALUES ('Free Gift Card For Steam & Amazon', 5);
INSERT INTO `appname_ct` VALUES ('欣欣汽车', 5);
INSERT INTO `appname_ct` VALUES ('天珠变系列全集', 1);
INSERT INTO `appname_ct` VALUES ('豪门恩怨小说精编', 11);
INSERT INTO `appname_ct` VALUES ('疯狂消豆豆', 14);
INSERT INTO `appname_ct` VALUES ('泰拉瑞亚（完整版）', 1);
INSERT INTO `appname_ct` VALUES ('透视之眼', 2);
INSERT INTO `appname_ct` VALUES ('儿童故事会', 1);
INSERT INTO `appname_ct` VALUES ('1010!', 98);
INSERT INTO `appname_ct` VALUES ('2012精排玄幻小说', 9);
INSERT INTO `appname_ct` VALUES ('择天记', 6);
INSERT INTO `appname_ct` VALUES ('眼保健操', 14);
INSERT INTO `appname_ct` VALUES ('Facebook立即上', 15);
INSERT INTO `appname_ct` VALUES ('小说人气榜', 7);
INSERT INTO `appname_ct` VALUES ('牙牙超级医生', 13);
INSERT INTO `appname_ct` VALUES ('3D迷宫', 1);
INSERT INTO `appname_ct` VALUES ('com.chancky.XuanYuanJian', 1);
INSERT INTO `appname_ct` VALUES ('神器看片', 1);
INSERT INTO `appname_ct` VALUES ('消灭星星 2 PopStars 2', 3);
INSERT INTO `appname_ct` VALUES ('满天星3', 1103);
INSERT INTO `appname_ct` VALUES ('儿童精品趣味拼图', 2);
INSERT INTO `appname_ct` VALUES ('网络最新言情小说', 5);
INSERT INTO `appname_ct` VALUES ('360小说大全', 3);
INSERT INTO `appname_ct` VALUES ('消灭星星 青春版', 6);
INSERT INTO `appname_ct` VALUES ('拼音快乐学', 4);
INSERT INTO `appname_ct` VALUES ('水果消消消', 5);
INSERT INTO `appname_ct` VALUES ('先锋影音', 1);
INSERT INTO `appname_ct` VALUES ('经典单机麻将', 30);
INSERT INTO `appname_ct` VALUES ('首席御医', 3);
INSERT INTO `appname_ct` VALUES ('快看', 2);
INSERT INTO `appname_ct` VALUES ('于晴全集', 1);
INSERT INTO `appname_ct` VALUES ('云视TV', 8);
INSERT INTO `appname_ct` VALUES ('星星狂欢', 1);
INSERT INTO `appname_ct` VALUES ('围棋宝典-科大', 1);
INSERT INTO `appname_ct` VALUES ('品牌特卖', 1);
INSERT INTO `appname_ct` VALUES ('分享赚钱 抢红包、话费', 537);
INSERT INTO `appname_ct` VALUES ('走遍美国同步中英字同步英汉简繁幕版免费版HD', 108);
INSERT INTO `appname_ct` VALUES ('新2048', 709);
INSERT INTO `appname_ct` VALUES ('aa', 8);
INSERT INTO `appname_ct` VALUES ('圣王', 1);
INSERT INTO `appname_ct` VALUES ('血战麻将', 1);
INSERT INTO `appname_ct` VALUES ('天天消消乐', 529);
INSERT INTO `appname_ct` VALUES ('糖果传奇', 1);
INSERT INTO `appname_ct` VALUES ('熊出没儿童益智拼图', 4);
INSERT INTO `appname_ct` VALUES ('红色仕途', 1);
INSERT INTO `appname_ct` VALUES ('午夜读书', 19);
INSERT INTO `appname_ct` VALUES ('小熊消消乐', 5);
INSERT INTO `appname_ct` VALUES ('2048', 50);
INSERT INTO `appname_ct` VALUES ('后宫如懿传', 4);
INSERT INTO `appname_ct` VALUES ('驾校达人 3D', 7);
INSERT INTO `appname_ct` VALUES ('周易算命占卜', 3);
INSERT INTO `appname_ct` VALUES ('多牛中国象棋', 4);
INSERT INTO `appname_ct` VALUES ('com.kkkstudio.doudizhu', 1);
INSERT INTO `appname_ct` VALUES ('波克棋牌', 1);
INSERT INTO `appname_ct` VALUES ('免费小说阅读器', 123);
INSERT INTO `appname_ct` VALUES ('官仙', 4);
INSERT INTO `appname_ct` VALUES ('最新情爱、言情小说＋玄幻武侠全本下载器', 3);
INSERT INTO `appname_ct` VALUES ('2048中文版', 6);
INSERT INTO `appname_ct` VALUES ('女总裁的贴身高手', 4);
INSERT INTO `appname_ct` VALUES ('PopStar消灭星星2', 4);
INSERT INTO `appname_ct` VALUES ('超级兵王', 1);
INSERT INTO `appname_ct` VALUES ('变声for微信', 1);
INSERT INTO `appname_ct` VALUES ('【TOP】言情小说精品全集', 138);
INSERT INTO `appname_ct` VALUES ('com.pptv.iphoneapp', 54);
INSERT INTO `appname_ct` VALUES ('新版驾校交规题库', 1);
INSERT INTO `appname_ct` VALUES ('开心猜成语', 1);
INSERT INTO `appname_ct` VALUES ('盘山公路3D', 14);
INSERT INTO `appname_ct` VALUES ('书橱小说', 8);
INSERT INTO `appname_ct` VALUES ('消灭星星夏季版', 15);
INSERT INTO `appname_ct` VALUES ('造化之门全集', 1);
INSERT INTO `appname_ct` VALUES ('补肾壮阳药膳', 4);
INSERT INTO `appname_ct` VALUES ('停车大师3D大卡车', 11);
INSERT INTO `appname_ct` VALUES ('名车坊', 10);
INSERT INTO `appname_ct` VALUES ('官神', 1);
INSERT INTO `appname_ct` VALUES ('天域苍穹系列全集', 2);
INSERT INTO `appname_ct` VALUES ('快听免费小说', 1);
INSERT INTO `appname_ct` VALUES ('天才相师', 1);
INSERT INTO `appname_ct` VALUES ('重生之官道 +免费阅读书小说漫画杂志电子书', 10);
INSERT INTO `appname_ct` VALUES ('叫叫大比拼', 15);
INSERT INTO `appname_ct` VALUES ('女性-ios', 106);
INSERT INTO `appname_ct` VALUES ('空当接龙', 45);
INSERT INTO `appname_ct` VALUES ('斗罗大陆2绝世唐门', 6);
INSERT INTO `appname_ct` VALUES ('易搜小说', 1);
INSERT INTO `appname_ct` VALUES ('五子连珠', 49);
INSERT INTO `appname_ct` VALUES ('见缝插针', 84);
INSERT INTO `appname_ct` VALUES ('总裁小说吧', 22);
INSERT INTO `appname_ct` VALUES ('木瓜影视大全', 2);
INSERT INTO `appname_ct` VALUES ('语录百科', 7);
INSERT INTO `appname_ct` VALUES ('消灭星星2014', 3);
INSERT INTO `appname_ct` VALUES ('◽坏蛋是怎样炼成的', 3);
INSERT INTO `appname_ct` VALUES ('天天精排txt小说电子书阅读器', 11);
INSERT INTO `appname_ct` VALUES ('读书', 1);
INSERT INTO `appname_ct` VALUES ('com.xunxin.doudizu', 11);
INSERT INTO `appname_ct` VALUES ('云阅书城 追书旗舰', 18);
INSERT INTO `appname_ct` VALUES ('佛经梵音', 4);
INSERT INTO `appname_ct` VALUES ('三字经童声朗诵', 1);
INSERT INTO `appname_ct` VALUES ('模拟汉堡店', 1);
INSERT INTO `appname_ct` VALUES ('com.brickbearstudios.games.popcat.ipad', 1);
INSERT INTO `appname_ct` VALUES ('消灭星星2016', 838);
INSERT INTO `appname_ct` VALUES ('很纯很暧昧全集', 1);
INSERT INTO `appname_ct` VALUES ('2013言情小说排行100本', 13);
INSERT INTO `appname_ct` VALUES ('香色闺阁小说阅读器', 1);
INSERT INTO `appname_ct` VALUES ('绝世高手在都市', 1);
INSERT INTO `appname_ct` VALUES ('船长泡泡龙', 5);
INSERT INTO `appname_ct` VALUES ('言情小说', 35);
INSERT INTO `appname_ct` VALUES ('开源中国', 3);
INSERT INTO `appname_ct` VALUES ('黑道特种兵', 1);
INSERT INTO `appname_ct` VALUES ('儿童数学乐园', 1);
INSERT INTO `appname_ct` VALUES ('玩丸', 9);
INSERT INTO `appname_ct` VALUES ('精品小说下载阅读器', 5);
INSERT INTO `appname_ct` VALUES ('天天泡泡龙', 5);
INSERT INTO `appname_ct` VALUES ('小学生作文', 1);
INSERT INTO `appname_ct` VALUES ('看图识字', 1);
INSERT INTO `appname_ct` VALUES ('玄幻小说', 72);
INSERT INTO `appname_ct` VALUES ('小说阅读榜', 78);
INSERT INTO `appname_ct` VALUES ('泡泡对对碰', 8);
INSERT INTO `appname_ct` VALUES ('消除之星 pop star!', 4);
INSERT INTO `appname_ct` VALUES ('内涵段子精选', 2);
INSERT INTO `appname_ct` VALUES ('斗鱼高清电影', 1);
INSERT INTO `appname_ct` VALUES ('天天看', 330);
INSERT INTO `appname_ct` VALUES ('笔趣阁快读玄幻书库', 1);
INSERT INTO `appname_ct` VALUES ('20几岁要懂得的100个说话技巧', 2);
INSERT INTO `appname_ct` VALUES ('掌上快读追书阅读器', 5);
INSERT INTO `appname_ct` VALUES ('余罪', 1);
INSERT INTO `appname_ct` VALUES ('星星消不停', 134);
INSERT INTO `appname_ct` VALUES ('全本小说阅读器', 55);
INSERT INTO `appname_ct` VALUES ('厕所兔矿工', 4);
INSERT INTO `appname_ct` VALUES ('星星连萌', 8);
INSERT INTO `appname_ct` VALUES ('医生游戏', 1);
INSERT INTO `appname_ct` VALUES ('基础韩语口语', 3);
INSERT INTO `appname_ct` VALUES ('泡泡龙完美版', 20);
INSERT INTO `appname_ct` VALUES ('升级游戏iPad免费版', 48);
INSERT INTO `appname_ct` VALUES ('全本小说合集', 7);
INSERT INTO `appname_ct` VALUES ('消灭星星新春版', 35);
INSERT INTO `appname_ct` VALUES ('Musical Brick', 28);
INSERT INTO `appname_ct` VALUES ('耽美小说全本精选合集', 38);
INSERT INTO `appname_ct` VALUES ('倪匡全集', 2);
INSERT INTO `appname_ct` VALUES ('盛名列车时刻表 for 12306 抢票', 4);
INSERT INTO `appname_ct` VALUES ('小说阅读榜HD', 4);
INSERT INTO `appname_ct` VALUES ('上瘾', 1);
INSERT INTO `appname_ct` VALUES ('com.lyl.zhiwencesuan3', 1);
INSERT INTO `appname_ct` VALUES ('都市奇门医圣', 1);
INSERT INTO `appname_ct` VALUES ('W.TV 手机电视', 3);
INSERT INTO `appname_ct` VALUES ('金庸小说合集', 1);
INSERT INTO `appname_ct` VALUES ('com.fungoTVHD.DianShiTVHD', 1);
INSERT INTO `appname_ct` VALUES ('内涵图片段子', 1);
INSERT INTO `appname_ct` VALUES ('pop star!星星消灭', 124);
INSERT INTO `appname_ct` VALUES ('言情小说吧', 12);
INSERT INTO `appname_ct` VALUES ('2013玄幻小说畅销榜', 1);
INSERT INTO `appname_ct` VALUES ('坏蛋是怎样炼成的2', 1);
INSERT INTO `appname_ct` VALUES ('花心碰碰', 186);
INSERT INTO `appname_ct` VALUES ('星星爱消除', 2);
INSERT INTO `appname_ct` VALUES ('最经典的恐怖小说', 1);
INSERT INTO `appname_ct` VALUES ('com.esbook.reader', 2);
INSERT INTO `appname_ct` VALUES ('增高有方法', 1);
INSERT INTO `appname_ct` VALUES ('最经典言情小说合集【最火】【免费看书+免费书城】', 1);
INSERT INTO `appname_ct` VALUES ('全本小说离线读书', 49);
INSERT INTO `appname_ct` VALUES ('快看玄幻小说连载书城', 9);
INSERT INTO `appname_ct` VALUES ('《故事会》十年合集', 1);
INSERT INTO `appname_ct` VALUES ('停车大师3D 圣诞节', 1);
INSERT INTO `appname_ct` VALUES ('赚钱三国', 113);
INSERT INTO `appname_ct` VALUES ('宫斗言情', 73);
INSERT INTO `appname_ct` VALUES ('升级', 12);
INSERT INTO `appname_ct` VALUES ('飞行棋', 25);
INSERT INTO `appname_ct` VALUES ('安卓节能手电筒', 9);
INSERT INTO `appname_ct` VALUES ('星星消灭了3', 29);
INSERT INTO `appname_ct` VALUES ('听歌识名篇', 7);
INSERT INTO `appname_ct` VALUES ('单机四川麻将', 1);
INSERT INTO `appname_ct` VALUES ('古灵小说全集', 1);
INSERT INTO `appname_ct` VALUES ('星星对战', 98);
INSERT INTO `appname_ct` VALUES ('经典穿越小说33部', 23);
INSERT INTO `appname_ct` VALUES ('萌宠爱消除', 3);
INSERT INTO `appname_ct` VALUES ('笔下文学', 6);
INSERT INTO `appname_ct` VALUES ('%2525E5%2525BF%2525AB%2525E9%252580%252592%2525E9%252580%25259F%2525E6%25259F%2525A5', 1);
INSERT INTO `appname_ct` VALUES ('围棋死活练习初级', 1);
INSERT INTO `appname_ct` VALUES ('搞笑妹子', 17);
INSERT INTO `appname_ct` VALUES ('每日智力题', 3);
INSERT INTO `appname_ct` VALUES ('唐寅在异界', 1);
INSERT INTO `appname_ct` VALUES ('汽车资讯', 2);
INSERT INTO `appname_ct` VALUES ('袁腾飞笑侃历史【有声珍藏版】', 1);
INSERT INTO `appname_ct` VALUES ('校花的贴身高手等鱼人二代小说作品全集', 15);
INSERT INTO `appname_ct` VALUES ('经典英语儿歌', 1);
INSERT INTO `appname_ct` VALUES ('穿越架空小说', 1);
INSERT INTO `appname_ct` VALUES ('方块联盟小游戏', 1);
INSERT INTO `appname_ct` VALUES ('全搜小说', 26);
INSERT INTO `appname_ct` VALUES ('逗比妹子传', 6);
INSERT INTO `appname_ct` VALUES ('励志语', 1);
INSERT INTO `appname_ct` VALUES ('好豆菜谱', 7139);
INSERT INTO `appname_ct` VALUES ('爸爸去哪儿2', 113);
INSERT INTO `appname_ct` VALUES ('【有声】坏蛋是怎样炼成的全集', 1);
INSERT INTO `appname_ct` VALUES ('琅琊榜', 1);
INSERT INTO `appname_ct` VALUES ('免费书旗小说', 4);
INSERT INTO `appname_ct` VALUES ('孝道', 278);
INSERT INTO `appname_ct` VALUES ('聚力视频', 908);
INSERT INTO `appname_ct` VALUES ('网游小说精选排行榜+免费下载海量小说', 2);
INSERT INTO `appname_ct` VALUES ('经典挖坑', 16);
INSERT INTO `appname_ct` VALUES ('淘小说', 1);
INSERT INTO `appname_ct` VALUES ('2013玄幻小说精选排行榜', 54);
INSERT INTO `appname_ct` VALUES ('看书神器', 7);
INSERT INTO `appname_ct` VALUES ('PopStar！消灭星星官方正版', 1792);
INSERT INTO `appname_ct` VALUES ('未知', 197);
INSERT INTO `appname_ct` VALUES ('脑力训练', 125);
INSERT INTO `appname_ct` VALUES ('全本小说离线读HD【豪华精排免费书城】', 43);
INSERT INTO `appname_ct` VALUES ('2014版高分言情小说100部全本大合集', 3);
INSERT INTO `appname_ct` VALUES ('魔法冰淇淋', 3);
INSERT INTO `appname_ct` VALUES ('有声大讲堂', 54);
INSERT INTO `appname_ct` VALUES ('五子棋', 34);
INSERT INTO `appname_ct` VALUES ('水果连连看大全', 11);
INSERT INTO `appname_ct` VALUES ('都市言情小说全本精选', 3);
INSERT INTO `appname_ct` VALUES ('彩球别跑', 31);
INSERT INTO `appname_ct` VALUES ('快读免费小说', 405);
INSERT INTO `appname_ct` VALUES ('完本小说', 1);
INSERT INTO `appname_ct` VALUES ('生活小贴士', 2);
INSERT INTO `appname_ct` VALUES ('官道无疆', 1);
INSERT INTO `appname_ct` VALUES ('马上赚钱', 18084);
INSERT INTO `appname_ct` VALUES ('师士传说', 3);
INSERT INTO `appname_ct` VALUES ('奥特曼填色', 4);
INSERT INTO `appname_ct` VALUES ('穿越合集', 55);
INSERT INTO `appname_ct` VALUES ('泡泡龙-经典版', 5);
INSERT INTO `appname_ct` VALUES ('PopCandy HD', 1);
INSERT INTO `appname_ct` VALUES ('消灭星星-科大', 1504);
INSERT INTO `appname_ct` VALUES ('汽车-ios', 73);
INSERT INTO `appname_ct` VALUES ('【宫斗穿越】小说大合集 ＋【精品】免费中文书城', 77);
INSERT INTO `appname_ct` VALUES ('唯美小说馆', 5);
INSERT INTO `appname_ct` VALUES ('经典空当接龙', 5);
INSERT INTO `appname_ct` VALUES ('罗辑思维', 1);
INSERT INTO `appname_ct` VALUES ('流行之星', 1074);
INSERT INTO `appname_ct` VALUES ('少儿小百科全册', 4);
INSERT INTO `appname_ct` VALUES ('芒果影音', 3);
INSERT INTO `appname_ct` VALUES ('后宫小说大合集 手掌阅读书小说免费书城', 2);
INSERT INTO `appname_ct` VALUES ('新五子连珠', 11);
INSERT INTO `appname_ct` VALUES ('户外健身', 241);
INSERT INTO `appname_ct` VALUES ('全本小说书城', 361);
INSERT INTO `appname_ct` VALUES ('养鬼为祸', 3);
INSERT INTO `appname_ct` VALUES ('小3传奇 Threes!', 22);
INSERT INTO `appname_ct` VALUES ('混沌天体', 1);
INSERT INTO `appname_ct` VALUES ('猫狗大战', 1744);
INSERT INTO `appname_ct` VALUES ('免费书城', 230);
INSERT INTO `appname_ct` VALUES ('七彩连珠', 23);
INSERT INTO `appname_ct` VALUES ('阅读软件', 2);
INSERT INTO `appname_ct` VALUES ('com.sinyee.babybus.dining', 1);
INSERT INTO `appname_ct` VALUES ('萌宝去哪儿', 128);
INSERT INTO `appname_ct` VALUES ('免费vip小说', 5);
INSERT INTO `appname_ct` VALUES ('极品家丁 图书云集的免费小说下载阅读神器', 9);
INSERT INTO `appname_ct` VALUES ('不被理解的毛泽东 ＋免费小说下载阅读追书神器', 6);
INSERT INTO `appname_ct` VALUES ('光头强洗车', 1);
INSERT INTO `appname_ct` VALUES ('毕方免费小说', 73);
INSERT INTO `appname_ct` VALUES ('盗墓笔记', 6);
INSERT INTO `appname_ct` VALUES ('都市言情小说全本排行榜', 7);
INSERT INTO `appname_ct` VALUES ('天天暴开心', 3);
INSERT INTO `appname_ct` VALUES ('疯狂猜对错', 1);
INSERT INTO `appname_ct` VALUES ('畅读免费小说', 1);
INSERT INTO `appname_ct` VALUES ('[有声]郭德纲', 5);
INSERT INTO `appname_ct` VALUES ('coinsKing', 2);
INSERT INTO `appname_ct` VALUES ('免费听书', 3);
INSERT INTO `appname_ct` VALUES ('单机拱猪', 11);
INSERT INTO `appname_ct` VALUES ('龙珠祖玛', 3);
INSERT INTO `appname_ct` VALUES ('最强狂兵', 2);
INSERT INTO `appname_ct` VALUES ('军棋翻翻棋', 6);
INSERT INTO `appname_ct` VALUES ('漫画大全', 12);
INSERT INTO `appname_ct` VALUES ('全本小说吧【免费书城】', 162);
INSERT INTO `appname_ct` VALUES ('官场小说全本精选合集', 10);
INSERT INTO `appname_ct` VALUES ('随身阅', 4);
INSERT INTO `appname_ct` VALUES ('开心泡泡狗', 2);
INSERT INTO `appname_ct` VALUES ('《故事会》八年珍藏合集电子阅读版', 5);
INSERT INTO `appname_ct` VALUES ('凌天战尊', 1);
INSERT INTO `appname_ct` VALUES ('果蔬连萌', 1);
INSERT INTO `appname_ct` VALUES ('愤怒的老奶奶', 2893);
INSERT INTO `appname_ct` VALUES ('将夜', 1);
INSERT INTO `appname_ct` VALUES ('主宰之王全集', 2);
INSERT INTO `appname_ct` VALUES ('水果碰碰 iFruitBop', 1);
INSERT INTO `appname_ct` VALUES ('最新穿越小说全本合集', 6);
INSERT INTO `appname_ct` VALUES ('拖拉机升级', 120);
INSERT INTO `appname_ct` VALUES ('单机斗地主', 654);
INSERT INTO `appname_ct` VALUES ('御鉴收藏', 274);
INSERT INTO `appname_ct` VALUES ('绝世武神等2015精排玄幻小说连载', 4);
INSERT INTO `appname_ct` VALUES ('消灭星星3 满天星', 42);
INSERT INTO `appname_ct` VALUES ('最热网络小说', 12);
INSERT INTO `appname_ct` VALUES ('单机双扣', 3);
INSERT INTO `appname_ct` VALUES ('豪门总裁小说精选', 1);
INSERT INTO `appname_ct` VALUES ('2013言情小说48部', 2);
INSERT INTO `appname_ct` VALUES ('2013穿越小说60部排行榜', 1);
INSERT INTO `appname_ct` VALUES ('爱奇艺', 35027);
INSERT INTO `appname_ct` VALUES ('单机麻将', 391);
INSERT INTO `appname_ct` VALUES ('免费看书软件', 18);
INSERT INTO `appname_ct` VALUES ('三界独尊', 3);
INSERT INTO `appname_ct` VALUES ('话匣子听书', 1);
INSERT INTO `appname_ct` VALUES ('武逆', 2);
INSERT INTO `appname_ct` VALUES ('停车大师3D2', 17);
INSERT INTO `appname_ct` VALUES ('快递查查', 40);
INSERT INTO `appname_ct` VALUES ('金萱全集', 4);
INSERT INTO `appname_ct` VALUES ('一个都不能死', 1);
INSERT INTO `appname_ct` VALUES ('天才儿子腹黑娘亲', 1);
INSERT INTO `appname_ct` VALUES ('绝世唐门', 1);
INSERT INTO `appname_ct` VALUES ('小说阅读器', 1713);
INSERT INTO `appname_ct` VALUES ('2D桌球', 97);
INSERT INTO `appname_ct` VALUES ('方块消消乐', 182);
INSERT INTO `appname_ct` VALUES ('梦入神机作品集', 3);
INSERT INTO `appname_ct` VALUES ('奥特曼拼图', 2);
INSERT INTO `appname_ct` VALUES ('无限恐怖全集', 2);
INSERT INTO `appname_ct` VALUES ('家常菜谱', 4);
INSERT INTO `appname_ct` VALUES ('校园全能高手', 1);
INSERT INTO `appname_ct` VALUES ('百度魔图', 8);
INSERT INTO `appname_ct` VALUES ('友阅', 7);
INSERT INTO `appname_ct` VALUES ('拼来拼趣', 7);
INSERT INTO `appname_ct` VALUES ('中国象棋残局大全', 6);
INSERT INTO `appname_ct` VALUES ('消灭水果', 1);
INSERT INTO `appname_ct` VALUES ('小说全本免费版', 2);
INSERT INTO `appname_ct` VALUES ('2012最新言情小说', 24);
INSERT INTO `appname_ct` VALUES ('2048！中文版', 14);
INSERT INTO `appname_ct` VALUES ('升级 拖拉机免费版', 20);
INSERT INTO `appname_ct` VALUES ('英汉互译离线', 10);
INSERT INTO `appname_ct` VALUES ('日语背单词', 2);
INSERT INTO `appname_ct` VALUES ('财经杂志', 3);
INSERT INTO `appname_ct` VALUES ('乖宝宝', 10);
INSERT INTO `appname_ct` VALUES ('中国天气通旗舰版', 4);
INSERT INTO `appname_ct` VALUES ('美丽书语', 3);
INSERT INTO `appname_ct` VALUES ('全本小说大全', 3);
INSERT INTO `appname_ct` VALUES ('蕃茄阅读', 201);
INSERT INTO `appname_ct` VALUES ('纵横顶点小说云阅读', 25);
INSERT INTO `appname_ct` VALUES ('消灭星星-全民升级版', 10);
INSERT INTO `appname_ct` VALUES ('言情小说【吧】', 2);
INSERT INTO `appname_ct` VALUES ('萌萌消消乐', 30);
INSERT INTO `appname_ct` VALUES ('反恐保卫战', 32);
INSERT INTO `appname_ct` VALUES ('穿越言情小说2013排行', 2);
INSERT INTO `appname_ct` VALUES ('唐家三少作品全集', 1);
INSERT INTO `appname_ct` VALUES ('中国农贸网', 368);
INSERT INTO `appname_ct` VALUES ('斗地主单机版', 51);
INSERT INTO `appname_ct` VALUES ('星之消除!pop star', 7);
INSERT INTO `appname_ct` VALUES ('么么答', 49);
INSERT INTO `appname_ct` VALUES ('女性-and', 502);
INSERT INTO `appname_ct` VALUES ('全番单机麻将', 7);
INSERT INTO `appname_ct` VALUES ('官场小说精选', 5);
INSERT INTO `appname_ct` VALUES ('子丑寅卯取名软件', 1);
INSERT INTO `appname_ct` VALUES ('满天星', 3);
INSERT INTO `appname_ct` VALUES ('情感心语', 13);
INSERT INTO `appname_ct` VALUES ('驾校一点通', 4);
INSERT INTO `appname_ct` VALUES ('侦探事务所', 1);
INSERT INTO `appname_ct` VALUES ('人生智慧', 4);
INSERT INTO `appname_ct` VALUES ('Pop.shenlan.com', 1);
INSERT INTO `appname_ct` VALUES ('小鸟对对碰', 1);
INSERT INTO `appname_ct` VALUES ('风行视频', 3315);
INSERT INTO `appname_ct` VALUES ('2013最火言情小说', 100);
INSERT INTO `appname_ct` VALUES ('掌上图书馆【精选全本】', 13);
INSERT INTO `appname_ct` VALUES ('百度书城', 14);
INSERT INTO `appname_ct` VALUES ('com.sinyee.babybus.puzzle', 1);
INSERT INTO `appname_ct` VALUES ('彼得老哥', 2);
INSERT INTO `appname_ct` VALUES ('锄大地', 1);
INSERT INTO `appname_ct` VALUES ('挖坑', 37);
INSERT INTO `appname_ct` VALUES ('易经之奇门遁甲', 5);
INSERT INTO `appname_ct` VALUES ('免费小说大全', 1);
INSERT INTO `appname_ct` VALUES ('微红包', 122);
INSERT INTO `appname_ct` VALUES ('小说下载阅读器', 41);
INSERT INTO `appname_ct` VALUES ('WiFi万能钥匙', 6);
INSERT INTO `appname_ct` VALUES ('攻心说话术', 2);
INSERT INTO `appname_ct` VALUES ('穿越言情小说全本排行榜', 3);
INSERT INTO `appname_ct` VALUES ('进击的屌丝', 11);
INSERT INTO `appname_ct` VALUES ('消除星星', 6);
INSERT INTO `appname_ct` VALUES ('方块连爆', 46);
INSERT INTO `appname_ct` VALUES ('万能播放器', 15);
INSERT INTO `appname_ct` VALUES ('PopStar+ Lite', 9);
INSERT INTO `appname_ct` VALUES ('天天军棋', 4);
INSERT INTO `appname_ct` VALUES ('搞趣生活', 1);
INSERT INTO `appname_ct` VALUES ('塔鲁大冒险汉化版', 810);
INSERT INTO `appname_ct` VALUES ('Free Car Racing Games', 95);
INSERT INTO `appname_ct` VALUES ('畅销言情小说精选', 7);
INSERT INTO `appname_ct` VALUES ('天天水果消除', 11);
INSERT INTO `appname_ct` VALUES ('校花的贴身高手全集', 2);
INSERT INTO `appname_ct` VALUES ('驾驶员理论考试（安卓2.2）', 1);
INSERT INTO `appname_ct` VALUES ('天天爱阅读【免费网上书城】', 39);
INSERT INTO `appname_ct` VALUES ('爱看免费小说', 1);
INSERT INTO `appname_ct` VALUES ('叫叫接金蛋', 11);
INSERT INTO `appname_ct` VALUES ('熊出没之熊二清洁大作战', 2);
INSERT INTO `appname_ct` VALUES ('黑白棋', 1);
INSERT INTO `appname_ct` VALUES ('3D停车场 Parking 3D', 2);
INSERT INTO `appname_ct` VALUES ('365健康养生', 1);
INSERT INTO `appname_ct` VALUES ('PopStar!消灭星星', 3946);
INSERT INTO `appname_ct` VALUES ('星星消消乐', 459);
INSERT INTO `appname_ct` VALUES ('宠物消消乐', 1);
INSERT INTO `appname_ct` VALUES ('点亮智慧人生', 1);
INSERT INTO `appname_ct` VALUES ('重生之贼行天下', 2);
INSERT INTO `appname_ct` VALUES ('无忧试车', 2);
INSERT INTO `appname_ct` VALUES ('有声畅听', 3);
INSERT INTO `appname_ct` VALUES ('360手机浏览器', 278);
INSERT INTO `appname_ct` VALUES ('果冻爆爆乐 HD 3', 1);
INSERT INTO `appname_ct` VALUES ('俄罗斯方块', 2998);
INSERT INTO `appname_ct` VALUES ('网络经典言情小说', 35);
INSERT INTO `appname_ct` VALUES ('懒人听书', 64);
INSERT INTO `appname_ct` VALUES ('闹钟精灵', 135);
INSERT INTO `appname_ct` VALUES ('金馆长收集器', 28);
INSERT INTO `appname_ct` VALUES ('佛说无量寿经', 1);
INSERT INTO `appname_ct` VALUES ('最经典小说全本精选', 14);
INSERT INTO `appname_ct` VALUES ('香色闺阁', 2);
INSERT INTO `appname_ct` VALUES ('精品小说书城', 21);
INSERT INTO `appname_ct` VALUES ('轻读全本', 29);
INSERT INTO `appname_ct` VALUES ('沃行讯通(实时公交)', 24);
INSERT INTO `appname_ct` VALUES ('免费书库', 8);
INSERT INTO `appname_ct` VALUES ('情感私语', 5);
INSERT INTO `appname_ct` VALUES ('疯狂英语', 1);
INSERT INTO `appname_ct` VALUES ('红楼梦 有声朗读', 4);
INSERT INTO `appname_ct` VALUES ('雪鹰领主全集', 1);
INSERT INTO `appname_ct` VALUES ('宠物世界猫迷', 1);
INSERT INTO `appname_ct` VALUES ('驾校一点通-ios 科大', 201);
INSERT INTO `appname_ct` VALUES ('郭德纲相声之丑娘娘', 2);
INSERT INTO `appname_ct` VALUES ('书包悦读', 44);
INSERT INTO `appname_ct` VALUES ('宝宝养成好习惯', 4);
INSERT INTO `appname_ct` VALUES ('莽荒纪', 3);
INSERT INTO `appname_ct` VALUES ('养车资讯', 11);
INSERT INTO `appname_ct` VALUES ('恐怖灵异小说', 10);
INSERT INTO `appname_ct` VALUES ('［有声］言情小说2013精品大合集', 6);
INSERT INTO `appname_ct` VALUES ('2048冰雪版', 4);
INSERT INTO `appname_ct` VALUES ('拍拍拼图', 1);
INSERT INTO `appname_ct` VALUES ('停车大师 3D', 1);
INSERT INTO `appname_ct` VALUES ('消灭宝石', 152);
INSERT INTO `appname_ct` VALUES ('智言趣语', 8);
INSERT INTO `appname_ct` VALUES ('正宗258麻将', 3);
INSERT INTO `appname_ct` VALUES ('极品家丁', 1);
INSERT INTO `appname_ct` VALUES ('中国茶文化', 1);
INSERT INTO `appname_ct` VALUES ('借贷宝', 17);
INSERT INTO `appname_ct` VALUES ('经典武侠合集', 1);
INSERT INTO `appname_ct` VALUES ('随手电筒-科大', 240);
INSERT INTO `appname_ct` VALUES ('粉碎星星传奇', 13);
INSERT INTO `appname_ct` VALUES ('可可蜂', 73);
INSERT INTO `appname_ct` VALUES ('流氓艳遇记', 2);
INSERT INTO `appname_ct` VALUES ('万卷读书 多看精排全本书城免费下载海量电子书', 6);
INSERT INTO `appname_ct` VALUES ('旋转泡泡龙', 1);
INSERT INTO `appname_ct` VALUES ('看图猜成语2', 1);
INSERT INTO `appname_ct` VALUES ('RadioTunes 320x50 iOS', 1);
INSERT INTO `appname_ct` VALUES ('看图猜成语3', 1);
INSERT INTO `appname_ct` VALUES ('无尽武装', 4);
INSERT INTO `appname_ct` VALUES ('五子连珠3', 4);
INSERT INTO `appname_ct` VALUES ('欢乐泡泡', 74);
INSERT INTO `appname_ct` VALUES ('免费全本小说', 38);
INSERT INTO `appname_ct` VALUES ('焦土', 1);
INSERT INTO `appname_ct` VALUES ('暴风影音', 4107);
INSERT INTO `appname_ct` VALUES ('360WiFi', 126);
INSERT INTO `appname_ct` VALUES ('王国保卫战', 2);
INSERT INTO `appname_ct` VALUES ('淘淘小说', 16);
INSERT INTO `appname_ct` VALUES ('消灭星星（经典版）', 5);
INSERT INTO `appname_ct` VALUES ('新书源', 18);
INSERT INTO `appname_ct` VALUES ('专业调音器', 6);
INSERT INTO `appname_ct` VALUES ('幼儿园儿歌', 1);
INSERT INTO `appname_ct` VALUES ('免费看书', 404);
INSERT INTO `appname_ct` VALUES ('HouseWait', 7);
INSERT INTO `appname_ct` VALUES ('言情小说阅读器', 1);
INSERT INTO `appname_ct` VALUES ('任天堂N64模拟器', 3273);
INSERT INTO `appname_ct` VALUES ('台球大师专业版', 2070);
INSERT INTO `appname_ct` VALUES ('電視連續劇', 1);
INSERT INTO `appname_ct` VALUES ('2012最新穿越小说', 80);
INSERT INTO `appname_ct` VALUES ('合战忍者村', 1);
INSERT INTO `appname_ct` VALUES ('海岛之战', 123);
INSERT INTO `appname_ct` VALUES ('黑道风云二十年等黑道系列全集', 2);
INSERT INTO `appname_ct` VALUES ('玄幻小说【吧】', 7);
INSERT INTO `appname_ct` VALUES ('1010', 1);
INSERT INTO `appname_ct` VALUES ('[更新]郭德纲2013相声', 10);
INSERT INTO `appname_ct` VALUES ('GayPark', 5);
INSERT INTO `appname_ct` VALUES ('【免费】官场精选合集+最热门的小说聚集地', 22);
INSERT INTO `appname_ct` VALUES ('百思不得姐', 183);
INSERT INTO `appname_ct` VALUES ('宜搜小说', 241);
INSERT INTO `appname_ct` VALUES ('七界武神', 2);
INSERT INTO `appname_ct` VALUES ('计时器', 1);
INSERT INTO `appname_ct` VALUES ('汽车-and', 309);
INSERT INTO `appname_ct` VALUES ('PopStar! 消灭星星Lite', 7);
INSERT INTO `appname_ct` VALUES ('咱们结婚吧', 15);
INSERT INTO `appname_ct` VALUES ('资讯-ios', 84);
INSERT INTO `appname_ct` VALUES ('汉语词典', 1);
INSERT INTO `appname_ct` VALUES ('修仙狂徒', 6);
INSERT INTO `appname_ct` VALUES ('懒人小说阅读+男女性免费热门经典网络图书书城', 1);
INSERT INTO `appname_ct` VALUES ('单机掼蛋', 6);
INSERT INTO `appname_ct` VALUES ('小说vip章节免费阅读', 4);
INSERT INTO `appname_ct` VALUES ('午夜看书神器', 12);
INSERT INTO `appname_ct` VALUES ('俄罗斯方块2016新版', 99);
INSERT INTO `appname_ct` VALUES ('银行从业资格考试', 2);
INSERT INTO `appname_ct` VALUES ('推箱子', 9);
INSERT INTO `appname_ct` VALUES ('掌上糗百 搞笑图片福利视频糗事百科段子的娱乐社区', 29);
INSERT INTO `appname_ct` VALUES ('生辰星位 shangshengxingzuo', 84);
INSERT INTO `appname_ct` VALUES ('姓名生活体验', 38);
INSERT INTO `appname_ct` VALUES ('寸芒全集 +万部网络书城+言情玄幻武侠全本下载器', 6);
INSERT INTO `appname_ct` VALUES ('兽血沸腾合集 vip章节免费阅读', 4);
INSERT INTO `appname_ct` VALUES ('消灭星星4加强版', 5);
INSERT INTO `appname_ct` VALUES ('饥饿鲨进化', 233);
INSERT INTO `appname_ct` VALUES ('凡人修仙传全集', 5);
INSERT INTO `appname_ct` VALUES ('搏击王国', 185);
INSERT INTO `appname_ct` VALUES ('经典玄幻小说合集', 3);
INSERT INTO `appname_ct` VALUES ('全本小说网【免费书城】', 41);
INSERT INTO `appname_ct` VALUES ('看书神器免费小说', 8);
INSERT INTO `appname_ct` VALUES ('有声情爱小说', 9);
INSERT INTO `appname_ct` VALUES ('免费VIP读书', 5);
INSERT INTO `appname_ct` VALUES ('都市生活小说', 3);
INSERT INTO `appname_ct` VALUES ('微言心语', 2);
INSERT INTO `appname_ct` VALUES ('青蛙祖玛2016升级版', 1);
INSERT INTO `appname_ct` VALUES ('Gobang', 1);
INSERT INTO `appname_ct` VALUES ('一笔画', 6);
INSERT INTO `appname_ct` VALUES ('儿歌多多HD', 1);
INSERT INTO `appname_ct` VALUES ('儿童绘画涂色', 9);
INSERT INTO `appname_ct` VALUES ('波波女性', 4);
INSERT INTO `appname_ct` VALUES ('果宝三国', 5);
INSERT INTO `appname_ct` VALUES ('亦舒小说典藏合集', 1);
INSERT INTO `appname_ct` VALUES ('连点消除', 75);
INSERT INTO `appname_ct` VALUES ('掌上读书宝', 11);
INSERT INTO `appname_ct` VALUES ('诛仙全八册【珍藏版】 +海量精品书籍 完全免费！！', 1);
INSERT INTO `appname_ct` VALUES ('龙珠祖玛HD', 30);
INSERT INTO `appname_ct` VALUES ('左右腦實驗室', 81);
INSERT INTO `appname_ct` VALUES ('坦克大战经典版', 50);
INSERT INTO `appname_ct` VALUES ('◽紫川【全五部】+海量多看电子书', 6);
INSERT INTO `appname_ct` VALUES ('2013最新宫廷言情小说68本', 2);
INSERT INTO `appname_ct` VALUES ('【TOP】穿越小说全本精选+精编精排免费书城', 1);
INSERT INTO `appname_ct` VALUES ('国际象棋', 1);
INSERT INTO `appname_ct` VALUES ('2015最热黑道小说合集', 24);
INSERT INTO `appname_ct` VALUES ('免费读书', 19);
INSERT INTO `appname_ct` VALUES ('聚合漫画王', 18);
INSERT INTO `appname_ct` VALUES ('冰火魔厨全集', 1);
INSERT INTO `appname_ct` VALUES ('云中歌', 4);
INSERT INTO `appname_ct` VALUES ('Hitap Keyboard', 2);
INSERT INTO `appname_ct` VALUES ('PEP小学英语一年级上册点读', 7);
INSERT INTO `appname_ct` VALUES ('冷笑话阅读器', 1);
INSERT INTO `appname_ct` VALUES ('异世邪君', 3);
INSERT INTO `appname_ct` VALUES ('泡泡龙hd', 1);
INSERT INTO `appname_ct` VALUES ('字体管家', 2);
INSERT INTO `appname_ct` VALUES ('玩转诈金花', 2);
INSERT INTO `appname_ct` VALUES ('数独', 104);
INSERT INTO `appname_ct` VALUES ('糖果消消乐', 15);
INSERT INTO `appname_ct` VALUES ('经典单机斗地主', 24);
INSERT INTO `appname_ct` VALUES ('欢乐填字', 1);
INSERT INTO `appname_ct` VALUES ('【更新】晓说+最新季外篇', 17);
INSERT INTO `appname_ct` VALUES ('末世神座', 1);
INSERT INTO `appname_ct` VALUES ('消除寂寞', 68);
INSERT INTO `appname_ct` VALUES ('逻辑大挑战 HD', 99);
INSERT INTO `appname_ct` VALUES ('午夜书城', 2);
INSERT INTO `appname_ct` VALUES ('爸爸去哪儿2内测版', 5);
INSERT INTO `appname_ct` VALUES ('好读小说', 1);
INSERT INTO `appname_ct` VALUES ('儿童拼图游戏', 2);
INSERT INTO `appname_ct` VALUES ('穿越小说【吧】', 3);
INSERT INTO `appname_ct` VALUES ('最新全本小说点击榜', 140);
INSERT INTO `appname_ct` VALUES ('全本免费小说＋精排完本书城', 19);
INSERT INTO `appname_ct` VALUES ('实习生', 1);
INSERT INTO `appname_ct` VALUES ('武动乾坤全集', 4);
INSERT INTO `appname_ct` VALUES ('数独达人', 13);
INSERT INTO `appname_ct` VALUES ('微信锁', 1);
INSERT INTO `appname_ct` VALUES ('追书', 1);
INSERT INTO `appname_ct` VALUES ('网络原创小说人气榜', 23);
INSERT INTO `appname_ct` VALUES ('书包小说阅读', 22);
INSERT INTO `appname_ct` VALUES ('秘密花园', 5);
INSERT INTO `appname_ct` VALUES ('免费VIP小说', 17);
INSERT INTO `appname_ct` VALUES ('医统江山全集', 1);
INSERT INTO `appname_ct` VALUES ('连连看', 1);
INSERT INTO `appname_ct` VALUES ('阅读星', 1);
INSERT INTO `appname_ct` VALUES ('单机欢乐斗地主', 9);
INSERT INTO `appname_ct` VALUES ('官场规则', 1);
INSERT INTO `appname_ct` VALUES ('不良之年少轻狂', 1);
INSERT INTO `appname_ct` VALUES ('楚留香全集', 3);
INSERT INTO `appname_ct` VALUES ('史上最坑爹的游戏5', 2);
INSERT INTO `appname_ct` VALUES ('学霸猜成语', 2);
INSERT INTO `appname_ct` VALUES ('【有声】午夜灵异怪谈', 1);
INSERT INTO `appname_ct` VALUES ('简洁浏览器', 1);
INSERT INTO `appname_ct` VALUES ('拳打脚踢麻将', 1);
INSERT INTO `appname_ct` VALUES ('梦幻盒子 for 梦幻西游电脑版', 1);
INSERT INTO `appname_ct` VALUES ('宝宝趣味学数字', 1);
INSERT INTO `appname_ct` VALUES ('365免费小说', 176);
INSERT INTO `appname_ct` VALUES ('免费小说', 364);
INSERT INTO `appname_ct` VALUES ('蜘蛛纸牌', 148);
INSERT INTO `appname_ct` VALUES ('首度汽车资讯', 11);
INSERT INTO `appname_ct` VALUES ('2048俄罗斯方块', 16);
INSERT INTO `appname_ct` VALUES ('史上最坑爹的游戏8', 2);
INSERT INTO `appname_ct` VALUES ('搜小说', 1);
INSERT INTO `appname_ct` VALUES ('【言情小说吧】', 186);
INSERT INTO `appname_ct` VALUES ('尊客', 264);
INSERT INTO `appname_ct` VALUES ('芈月传有声小说', 36);
INSERT INTO `appname_ct` VALUES ('减肥塑身', 83);
INSERT INTO `appname_ct` VALUES ('消灭星星传奇', 3);
INSERT INTO `appname_ct` VALUES ('微语录', 16);
INSERT INTO `appname_ct` VALUES ('全本小说精品书城', 4);
INSERT INTO `appname_ct` VALUES ('泡泡龙II', 1);
INSERT INTO `appname_ct` VALUES ('会计初级职称考试', 16);
INSERT INTO `appname_ct` VALUES ('2014穿越小说100部珍藏版', 6);
INSERT INTO `appname_ct` VALUES ('最火全本小说排行榜', 10);
INSERT INTO `appname_ct` VALUES ('经典网络小说', 3);
INSERT INTO `appname_ct` VALUES ('看图猜成语', 2);
INSERT INTO `appname_ct` VALUES ('中国象棋', 407);
INSERT INTO `appname_ct` VALUES ('2013小说全本精选榜', 1043);
INSERT INTO `appname_ct` VALUES ('ATM Pocket', 29);
INSERT INTO `appname_ct` VALUES ('书城小说', 160);
INSERT INTO `appname_ct` VALUES ('神庙逃亡2', 1332);
INSERT INTO `appname_ct` VALUES ('澳门方块', 788);
INSERT INTO `appname_ct` VALUES ('修真全本', 7);
INSERT INTO `appname_ct` VALUES ('妈妈讲故事系列合集', 1);
INSERT INTO `appname_ct` VALUES ('升级 拖拉机', 123);
INSERT INTO `appname_ct` VALUES ('成语玩命猜', 5);
INSERT INTO `appname_ct` VALUES ('云端书城 快看小说阅读追书神器', 11);
INSERT INTO `appname_ct` VALUES ('狂神全集', 1);
INSERT INTO `appname_ct` VALUES ('找茬猫', 75);
INSERT INTO `appname_ct` VALUES ('免费小说阅读', 7);
INSERT INTO `appname_ct` VALUES ('电子书', 9);
INSERT INTO `appname_ct` VALUES ('房贷计算器', 1);
INSERT INTO `appname_ct` VALUES ('每日必读', 1);
INSERT INTO `appname_ct` VALUES ('鳄鱼小顽皮爱洗澡', 494);
INSERT INTO `appname_ct` VALUES ('应用锁', 10);
INSERT INTO `appname_ct` VALUES ('情感语录', 3);
INSERT INTO `appname_ct` VALUES ('果蔬连连看', 14);
INSERT INTO `appname_ct` VALUES ('爱车之家', 7);
INSERT INTO `appname_ct` VALUES ('赘婿', 3);
INSERT INTO `appname_ct` VALUES ('豌豆阅读', 1);
INSERT INTO `appname_ct` VALUES ('摇一摇手电筒', 1);
INSERT INTO `appname_ct` VALUES ('驾考模拟3D', 18);
INSERT INTO `appname_ct` VALUES ('水果连连看', 79);
INSERT INTO `appname_ct` VALUES ('畅听言情', 3);
INSERT INTO `appname_ct` VALUES ('绝世武神', 2);
INSERT INTO `appname_ct` VALUES ('全景新闻直播', 1);
INSERT INTO `appname_ct` VALUES ('饥饿鲨：进化', 103);
INSERT INTO `appname_ct` VALUES ('天涯论坛精选', 4);
INSERT INTO `appname_ct` VALUES ('91看书', 9);
INSERT INTO `appname_ct` VALUES ('免费阅读器', 431);
INSERT INTO `appname_ct` VALUES ('总裁言情精选', 6);
INSERT INTO `appname_ct` VALUES ('单机升级', 9);
INSERT INTO `appname_ct` VALUES ('Facebook Now', 4);
INSERT INTO `appname_ct` VALUES ('玛丽消消乐', 2);
INSERT INTO `appname_ct` VALUES ('刀剑神皇', 1);
INSERT INTO `appname_ct` VALUES ('精灵读书', 8);
INSERT INTO `appname_ct` VALUES ('环球军事', 2);
INSERT INTO `appname_ct` VALUES ('现代都市异能小说精选合集', 4);
INSERT INTO `appname_ct` VALUES ('每日红包 马上赚钱', 1051);
INSERT INTO `appname_ct` VALUES ('星星大爆炸', 3);
INSERT INTO `appname_ct` VALUES ('地铁跑酷', 723);
INSERT INTO `appname_ct` VALUES ('搜狐新闻', 310);
INSERT INTO `appname_ct` VALUES ('养生有道', 6);
INSERT INTO `appname_ct` VALUES ('他来了请闭眼', 1);
INSERT INTO `appname_ct` VALUES ('疯狂猜成语', 1);
INSERT INTO `appname_ct` VALUES ('BB弹', 2);
INSERT INTO `appname_ct` VALUES ('军事新闻', 4);
INSERT INTO `appname_ct` VALUES ('遮天全集', 4);
INSERT INTO `appname_ct` VALUES ('热门小说免费VIP', 10);
INSERT INTO `appname_ct` VALUES ('【免费】天涯热书排行榜 +海量精品免费书城', 15);
INSERT INTO `appname_ct` VALUES ('诛仙完本小说', 32);
INSERT INTO `appname_ct` VALUES ('我要买玩具', 6);
INSERT INTO `appname_ct` VALUES ('Pop Star! 星消消', 27);
INSERT INTO `appname_ct` VALUES ('网络小说全本精选', 67);
INSERT INTO `appname_ct` VALUES ('无尽之战', 1);
INSERT INTO `appname_ct` VALUES ('消除之星', 7);
INSERT INTO `appname_ct` VALUES ('爱读电子书', 2);
INSERT INTO `appname_ct` VALUES ('2014言情小说+最新免费连载小说/全本小说+最火/畅销/网络/言', 2);
INSERT INTO `appname_ct` VALUES ('财经电视精选', 2);
INSERT INTO `appname_ct` VALUES ('新交规驾照考试', 1);
INSERT INTO `appname_ct` VALUES ('2048六边形版', 5);
INSERT INTO `appname_ct` VALUES ('数独经典', 2);
INSERT INTO `appname_ct` VALUES ('天涯论坛', 2);
INSERT INTO `appname_ct` VALUES ('免费看小说', 13);
INSERT INTO `appname_ct` VALUES ('2013穿越小说100部典藏', 3);
INSERT INTO `appname_ct` VALUES ('会计从业资格考试', 21);
INSERT INTO `appname_ct` VALUES ('唐诗三百首完整典藏注音解析版HD', 18);
INSERT INTO `appname_ct` VALUES ('郭德纲2014最新相声', 1);
INSERT INTO `appname_ct` VALUES ('穿越小说2013选编', 4);
INSERT INTO `appname_ct` VALUES ('PopStar Plus', 2);
INSERT INTO `appname_ct` VALUES ('三国KILL', 13);
INSERT INTO `appname_ct` VALUES ('懒人读书', 6);
INSERT INTO `appname_ct` VALUES ('穿越小说', 3);
INSERT INTO `appname_ct` VALUES ('电子书阅读书城', 2);
INSERT INTO `appname_ct` VALUES ('畅销玄幻小说', 12);
INSERT INTO `appname_ct` VALUES ('水晶泡泡龙', 2);
INSERT INTO `appname_ct` VALUES ('全本免费书城', 4);
INSERT INTO `appname_ct` VALUES ('com.pplive.androidphone', 176);
INSERT INTO `appname_ct` VALUES ('某瓣 图书排行榜', 35);
INSERT INTO `appname_ct` VALUES ('读书软件', 1);
INSERT INTO `appname_ct` VALUES ('三年级上英语点读', 1);
INSERT INTO `appname_ct` VALUES ('动动脑子-疯狂脑筋急转弯', 9);
INSERT INTO `appname_ct` VALUES ('面相风水', 201);
INSERT INTO `appname_ct` VALUES ('诛仙青云志全集', 2);
INSERT INTO `appname_ct` VALUES ('雪中悍刀行', 1);
INSERT INTO `appname_ct` VALUES ('异世超能小说排行', 2);
INSERT INTO `appname_ct` VALUES ('安卓壁纸', 767);
INSERT INTO `appname_ct` VALUES ('BB弹-超沉迷', 76);
INSERT INTO `appname_ct` VALUES ('豆瓣高分小说大合集', 66);
INSERT INTO `appname_ct` VALUES ('全本小说免费阅读', 15);
INSERT INTO `appname_ct` VALUES ('酷匠天蚕土豆玄幻合集', 8);
INSERT INTO `appname_ct` VALUES ('咕咕收音机', 2);
INSERT INTO `appname_ct` VALUES ('财经', 3);
INSERT INTO `appname_ct` VALUES ('中国风水全书', 1);

-- ----------------------------
-- Table structure for client_ct
-- ----------------------------
DROP TABLE IF EXISTS `client_ct`;
CREATE TABLE `client_ct`  (
  `client` varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `clientct` bigint(20) NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of client_ct
-- ----------------------------
INSERT INTO `client_ct` VALUES ('android ', 160999);
INSERT INTO `client_ct` VALUES ('ios ', 41400);
INSERT INTO `client_ct` VALUES ('未知', 875);

-- ----------------------------
-- Table structure for isp_ct
-- ----------------------------
DROP TABLE IF EXISTS `isp_ct`;
CREATE TABLE `isp_ct`  (
  `ispname` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `ispct` bigint(20) NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of isp_ct
-- ----------------------------
INSERT INTO `isp_ct` VALUES ('移动', 268232);
INSERT INTO `isp_ct` VALUES ('联通', 217104);
INSERT INTO `isp_ct` VALUES ('电信', 166931);
INSERT INTO `isp_ct` VALUES ('未知', 181007);

-- ----------------------------
-- Table structure for network_ct
-- ----------------------------
DROP TABLE IF EXISTS `network_ct`;
CREATE TABLE `network_ct`  (
  `networkmannername` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `networkct` bigint(20) NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of network_ct
-- ----------------------------
INSERT INTO `network_ct` VALUES ('4G', 8239);
INSERT INTO `network_ct` VALUES ('未知', 27972);
INSERT INTO `network_ct` VALUES ('Wifi', 157015);
INSERT INTO `network_ct` VALUES ('2G', 5277);
INSERT INTO `network_ct` VALUES ('3G', 4771);

-- ----------------------------
-- Table structure for rpt_ll
-- ----------------------------
DROP TABLE IF EXISTS `rpt_ll`;
CREATE TABLE `rpt_ll`  (
  `provincename` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `cityname` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `ysrequest` bigint(20) NULL DEFAULT NULL,
  `yxrequest` bigint(20) NULL DEFAULT NULL,
  `adrequest` bigint(20) NULL DEFAULT NULL,
  `cybid` bigint(20) NULL DEFAULT NULL,
  `cysuccess` bigint(20) NULL DEFAULT NULL,
  `shows` bigint(20) NULL DEFAULT NULL,
  `clicks` bigint(20) NULL DEFAULT NULL,
  `dspcost` double NULL DEFAULT NULL,
  `dspapy` double NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of rpt_ll
-- ----------------------------
INSERT INTO `rpt_ll` VALUES ('广东省', '阳江市', 1546, 1543, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '未知', 102, 102, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '商丘市', 321, 318, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '本溪市', 206, 203, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('宁夏回族自治区', '石嘴山市', 39, 39, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '安阳市', 363, 359, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '临汾市', 181, 179, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '鹰潭市', 112, 111, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '大庆市', 418, 418, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '红河哈尼族彝族自治州', 54, 54, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '延安市', 147, 147, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '河池市', 67, 67, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('贵州省', '六盘水市', 54, 49, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '郴州市', 157, 150, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '吐鲁番地区', 6, 6, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '绍兴市', 896, 884, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '三门峡市', 185, 183, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '巴音郭楞蒙古自治州', 44, 42, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('贵州省', '贵阳市', 692, 676, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('贵州省', '安顺市', 51, 49, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '泰州市', 553, 547, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '未知', 608, 601, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '白银市', 12, 12, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '通辽市', 473, 468, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '宜春市', 457, 454, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '陇南市', 19, 19, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '肇庆市', 88, 87, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '孝感市', 430, 423, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '邵阳市', 755, 752, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '未知', 492, 484, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '清远市', 101, 100, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '楚雄彝族自治州', 25, 25, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('福建省', '厦门市', 616, 605, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '苏州市', 2101, 2077, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '无锡市', 2137, 2126, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '未知', 139, 132, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '黄冈市', 357, 346, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('宁夏回族自治区', '银川市', 240, 237, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '巴中市', 59, 58, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '南通市', 868, 856, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '忻州市', 101, 101, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '汉中市', 89, 89, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('青海省', '黄南藏族自治州', 5, 5, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '阜阳市', 314, 307, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '潍坊市', 1113, 1096, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '广州市', 5094, 5063, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '襄樊市', 315, 310, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '怒江傈僳族自治州', 10, 10, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '嘉兴市', 812, 805, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '滨州市', 402, 398, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '玉溪市', 116, 116, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '双鸭山市', 77, 75, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('天津市', '天津市', 1623, 1586, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '菏泽市', 634, 629, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '洛阳市', 303, 296, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '鹤壁市', 85, 83, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '丽江市', 47, 44, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '湛江市', 306, 301, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '乌鲁木齐市', 266, 252, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '湘潭市', 96, 96, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '遂宁市', 90, 87, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '日照市', 387, 385, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '抚州市', 228, 222, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '防城港市', 13, 13, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '邢台市', 566, 560, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '焦作市', 358, 356, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('吉林省', '未知', 5, 5, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '台州市', 1329, 1301, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '鄂尔多斯市', 110, 109, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '宣城市', 261, 258, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '咸宁市', 115, 114, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '南阳市', 365, 364, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '景德镇市', 306, 303, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '武威市', 57, 57, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '韶关市', 176, 175, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '秦皇岛市', 322, 322, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '乌海市', 67, 66, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '益阳市', 29660, 29654, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '九江市', 471, 467, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '大同市', 298, 296, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '恩施土家族苗族自治州', 65, 60, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('吉林省', '延边朝鲜族自治州', 258, 257, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '石家庄市', 1767, 1729, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '铜陵市', 196, 194, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '随州市', 86, 83, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '鹤岗市', 288, 287, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '淮南市', 619, 615, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('澳门特别行政区', '澳门特别行政区', 8, 8, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '新乡市', 278, 277, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('宁夏回族自治区', '吴忠市', 12, 12, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '扬州市', 700, 679, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '廊坊市', 828, 826, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '绵阳市', 409, 407, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '抚顺市', 380, 379, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '曲靖市', 57, 56, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '塔城地区', 23, 23, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '和田地区', 12, 12, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '济宁市', 575, 565, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '株洲市', 145, 141, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '眉山市', 302, 301, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '保山市', 34, 34, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '广元市', 83, 83, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('西藏自治区', '林芝地区', 1, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '常德市', 249, 248, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '衢州市', 301, 298, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '酒泉市', 18, 18, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '资阳市', 73, 70, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '雅安市', 69, 68, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('贵州省', '未知', 10, 10, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '聊城市', 463, 453, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '阿坝藏族羌族自治州', 27, 26, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('宁夏回族自治区', '中卫市', 18, 18, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '宜昌市', 285, 284, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '张家口市', 180, 180, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '未知', 141, 140, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('西藏自治区', '山南地区', 4, 4, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '济南市', 1558, 1545, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '博尔塔拉蒙古自治州', 12, 12, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '内江市', 1317, 1300, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '未知', 42, 42, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '河源市', 120, 120, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '阿克苏地区', 17, 17, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '徐州市', 1658, 1617, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '大连市', 749, 739, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '喀什地区', 19, 15, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '北海市', 192, 192, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '合肥市', 3105, 3093, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '达州市', 177, 171, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '辽阳市', 688, 681, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '营口市', 340, 340, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '钦州市', 158, 158, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '蚌埠市', 249, 244, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '玉林市', 323, 320, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('上海市', '上海市', 4095, 4034, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '赤峰市', 288, 283, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '梅州市', 348, 347, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '丽水市', 269, 258, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('西藏自治区', '拉萨市', 67, 66, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '大理白族自治州', 30, 30, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '永州市', 252, 252, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '烟台市', 822, 799, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('未知', '未知', 780, 756, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '包头市', 157, 153, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '嘉峪关市', 5, 5, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '呼伦贝尔市', 244, 243, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '驻马店市', 227, 225, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('青海省', '海北藏族自治州', 2, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '佳木斯市', 420, 420, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '芜湖市', 238, 236, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('吉林省', '长春市', 1203, 1188, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '张掖市', 118, 117, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('吉林省', '辽源市', 269, 269, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '唐山市', 1449, 1433, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '东莞市', 969, 944, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '鸡西市', 275, 269, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '镇江市', 361, 355, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('贵州省', '黔西南布依族苗族自治未知', 49, 46, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '庆阳市', 60, 60, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('香港特别行政区', '香港特别行政区', 121, 121, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '濮阳市', 282, 281, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('吉林省', '吉林市', 922, 920, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '深圳市', 1497, 1476, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '泰安市', 418, 406, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '凉山彝族自治州', 68, 68, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '南宁市', 12938, 12931, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '成都市', 1277, 1257, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '宿州市', 270, 269, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '巴彦淖尔市', 48, 48, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('海南省', '三亚市', 11, 11, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '盐城市', 705, 692, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '江门市', 451, 448, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '定西市', 49, 49, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '沧州市', 965, 939, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('贵州省', '遵义市', 178, 171, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '乌兰察布市', 98, 96, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('吉林省', '白城市', 84, 82, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('青海省', '海西蒙古族藏族自治州', 4, 4, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '西双版纳傣族自治州', 50, 50, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '德宏傣族景颇族自治州', 39, 38, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('福建省', '泉州市', 1008, 992, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '荆州市', 214, 208, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '佛山市', 885, 864, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '淮安市', 628, 624, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '池州市', 128, 128, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '阿拉善盟', 14, 14, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '汕尾市', 172, 171, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '丹东市', 255, 255, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '舟山市', 261, 251, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '商洛市', 36, 36, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '温州市', 1988, 1955, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '泸州市', 133, 133, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '怀化市', 289, 284, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '柳州市', 396, 395, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '宿迁市', 517, 512, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '珠海市', 385, 371, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '来宾市', 74, 74, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('贵州省', '黔东南苗族侗族自治州', 111, 108, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '湘西土家族苗族自治州', 179, 179, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '铁岭市', 288, 287, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '莱芜市', 237, 237, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '金华市', 1144, 1121, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '赣州市', 555, 548, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('福建省', '龙岩市', 437, 411, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '亳州市', 240, 236, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('西藏自治区', '未知', 33, 32, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '兰州市', 393, 388, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '兴安盟', 44, 42, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '揭阳市', 256, 252, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('吉林省', '通化市', 207, 205, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '宜宾市', 240, 239, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '贺州市', 164, 164, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '锡林郭勒盟', 55, 51, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '大兴安岭地区', 49, 48, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '常州市', 950, 945, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '六安市', 251, 251, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '潮州市', 75, 74, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '锦州市', 180, 179, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '沈阳市', 1772, 1752, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '萍乡市', 246, 240, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('宁夏回族自治区', '未知', 1, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '南昌市', 2170, 2119, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('宁夏回族自治区', '固原市', 15, 15, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '吉安市', 250, 244, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '齐齐哈尔市', 205, 203, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '南京市', 2234, 2187, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '淮北市', 389, 387, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '百色市', 100, 99, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('吉林省', '四平市', 253, 252, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '七台河市', 102, 101, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '贵港市', 190, 190, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '德州市', 499, 496, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('重庆市', '重庆市', 2966, 2913, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '周口市', 435, 432, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '临沂市', 1148, 1144, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '茂名市', 198, 194, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '开封市', 235, 228, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '云浮市', 71, 67, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '保定市', 979, 947, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '滁州市', 247, 244, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '梧州市', 198, 197, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '马鞍山市', 278, 278, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '咸阳市', 319, 319, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '朝阳市', 134, 128, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '榆林市', 165, 164, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '伊春市', 38, 38, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '武汉市', 3087, 3035, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '十堰市', 255, 255, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '汕头市', 399, 398, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '东营市', 402, 401, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '普洱市', 105, 105, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '娄底市', 278, 275, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '鞍山市', 267, 265, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '荆门市', 87, 87, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '阳泉市', 320, 319, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '杭州市', 3877, 3809, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '阜新市', 381, 380, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '绥化市', 510, 509, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '西安市', 2794, 2770, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '临沧市', 12, 12, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '迪庆藏族自治州', 3, 3, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '平凉市', 12, 12, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('青海省', '未知', 14, 14, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '牡丹江市', 408, 406, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '长治市', 364, 362, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '未知', 31, 31, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '克孜勒苏柯尔克孜自治未知', 5, 5, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '未知', 743, 736, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '甘孜藏族自治州', 240, 239, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '临夏回族自治州', 13, 13, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '上饶市', 662, 637, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '惠州市', 515, 505, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('福建省', '宁德市', 270, 269, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '克拉玛依市', 21, 21, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('福建省', '福州市', 1412, 1355, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '许昌市', 401, 398, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('海南省', '未知', 107, 106, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '葫芦岛市', 252, 250, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '信阳市', 611, 607, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '漯河市', 138, 126, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '安庆市', 298, 296, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '未知', 48, 48, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '金昌市', 10, 10, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('台湾省', '未知', 1, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '南充市', 332, 332, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '昆明市', 613, 606, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '运城市', 247, 244, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '德阳市', 190, 190, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('辽宁省', '盘锦市', 103, 103, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('福建省', '三明市', 245, 231, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '枣庄市', 642, 634, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '昌吉回族自治州', 46, 44, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '桂林市', 396, 395, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '阿勒泰地区', 11, 11, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '宁波市', 1971, 1949, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '青岛市', 2272, 2261, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '衡水市', 543, 532, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('吉林省', '白山市', 51, 50, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '长沙市', 10431, 10389, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '郑州市', 2062, 2041, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '张家界市', 69, 68, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('贵州省', '黔南布依族苗族自治州', 97, 96, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('福建省', '漳州市', 599, 589, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '广安市', 184, 181, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '未知', 65, 65, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '黄石市', 126, 124, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '铜川市', 36, 36, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '黑河市', 124, 118, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('青海省', '果洛藏族自治州', 2, 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广西壮族自治区', '崇左市', 114, 113, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '吕梁市', 70, 70, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('福建省', '南平市', 251, 247, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '哈尔滨市', 1680, 1659, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '岳阳市', 795, 785, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('西藏自治区', '昌都地区', 1, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('青海省', '西宁市', 179, 176, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江苏省', '连云港市', 623, 614, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('福建省', '莆田市', 271, 268, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '甘南藏族自治州', 3, 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '呼和浩特市', 399, 394, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '鄂州市', 49, 49, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('青海省', '海南藏族自治州', 6, 6, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '邯郸市', 609, 586, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('北京市', '北京市', 4962, 4894, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '渭南市', 250, 246, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('黑龙江省', '未知', 2, 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '太原市', 683, 681, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('吉林省', '松原市', 312, 310, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '平顶山市', 254, 251, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河南省', '未知', 24, 22, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '晋中市', 426, 426, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '未知', 3, 3, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '文山壮族苗族自治州', 41, 39, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖南省', '衡阳市', 488, 486, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '乐山市', 166, 161, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '自贡市', 307, 305, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('四川省', '攀枝花市', 26, 25, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('安徽省', '黄山市', 177, 172, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '宝鸡市', 295, 293, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('河北省', '承德市', 236, 231, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('甘肃省', '天水市', 57, 56, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('内蒙古自治区', '未知', 15, 14, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('广东省', '中山市', 402, 399, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '未知', 101, 101, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('湖北省', '未知', 115, 115, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '晋城市', 142, 140, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('海南省', '海口市', 346, 342, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('云南省', '昭通市', 72, 70, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('陕西省', '安康市', 99, 99, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('浙江省', '湖州市', 644, 633, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '威海市', 531, 526, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '伊犁哈萨克自治州', 35, 35, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山西省', '朔州市', 52, 52, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('山东省', '淄博市', 406, 403, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('江西省', '新余市', 82, 80, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `rpt_ll` VALUES ('新疆维吾尔自治区', '哈密地区', 32, 32, 0, 0, 0, 0, 0, 0, 0);

-- ----------------------------
-- Table structure for rpt_pc_count
-- ----------------------------
DROP TABLE IF EXISTS `rpt_pc_count`;
CREATE TABLE `rpt_pc_count`  (
  `provincename` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `cityname` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `ct` bigint(20) NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of rpt_pc_count
-- ----------------------------
INSERT INTO `rpt_pc_count` VALUES ('广东省', '阳江市', 1546);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '未知', 102);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '商丘市', 321);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '本溪市', 206);
INSERT INTO `rpt_pc_count` VALUES ('宁夏回族自治区', '石嘴山市', 39);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '安阳市', 363);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '临汾市', 181);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '鹰潭市', 112);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '大庆市', 418);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '红河哈尼族彝族自治州', 54);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '延安市', 147);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '河池市', 67);
INSERT INTO `rpt_pc_count` VALUES ('贵州省', '六盘水市', 54);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '郴州市', 157);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '吐鲁番地区', 6);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '绍兴市', 896);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '三门峡市', 185);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '巴音郭楞蒙古自治州', 44);
INSERT INTO `rpt_pc_count` VALUES ('贵州省', '贵阳市', 692);
INSERT INTO `rpt_pc_count` VALUES ('贵州省', '安顺市', 51);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '泰州市', 553);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '未知', 608);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '白银市', 12);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '通辽市', 473);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '宜春市', 457);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '陇南市', 19);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '肇庆市', 88);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '孝感市', 430);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '邵阳市', 755);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '未知', 492);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '清远市', 101);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '楚雄彝族自治州', 25);
INSERT INTO `rpt_pc_count` VALUES ('福建省', '厦门市', 616);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '苏州市', 2101);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '无锡市', 2137);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '未知', 139);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '黄冈市', 357);
INSERT INTO `rpt_pc_count` VALUES ('宁夏回族自治区', '银川市', 240);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '巴中市', 59);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '南通市', 868);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '忻州市', 101);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '汉中市', 89);
INSERT INTO `rpt_pc_count` VALUES ('青海省', '黄南藏族自治州', 5);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '阜阳市', 314);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '潍坊市', 1113);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '广州市', 5094);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '襄樊市', 315);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '怒江傈僳族自治州', 10);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '嘉兴市', 812);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '滨州市', 402);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '玉溪市', 116);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '双鸭山市', 77);
INSERT INTO `rpt_pc_count` VALUES ('天津市', '天津市', 1623);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '菏泽市', 634);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '洛阳市', 303);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '鹤壁市', 85);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '丽江市', 47);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '湛江市', 306);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '乌鲁木齐市', 266);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '湘潭市', 96);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '遂宁市', 90);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '日照市', 387);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '抚州市', 228);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '防城港市', 13);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '邢台市', 566);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '焦作市', 358);
INSERT INTO `rpt_pc_count` VALUES ('吉林省', '未知', 5);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '台州市', 1329);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '鄂尔多斯市', 110);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '宣城市', 261);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '咸宁市', 115);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '南阳市', 365);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '景德镇市', 306);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '武威市', 57);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '韶关市', 176);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '秦皇岛市', 322);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '乌海市', 67);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '益阳市', 29660);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '九江市', 471);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '大同市', 298);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '恩施土家族苗族自治州', 65);
INSERT INTO `rpt_pc_count` VALUES ('吉林省', '延边朝鲜族自治州', 258);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '石家庄市', 1767);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '铜陵市', 196);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '随州市', 86);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '鹤岗市', 288);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '淮南市', 619);
INSERT INTO `rpt_pc_count` VALUES ('澳门特别行政区', '澳门特别行政区', 8);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '新乡市', 278);
INSERT INTO `rpt_pc_count` VALUES ('宁夏回族自治区', '吴忠市', 12);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '扬州市', 700);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '廊坊市', 828);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '绵阳市', 409);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '抚顺市', 380);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '曲靖市', 57);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '塔城地区', 23);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '和田地区', 12);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '济宁市', 575);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '株洲市', 145);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '眉山市', 302);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '保山市', 34);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '广元市', 83);
INSERT INTO `rpt_pc_count` VALUES ('西藏自治区', '林芝地区', 1);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '常德市', 249);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '衢州市', 301);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '酒泉市', 18);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '资阳市', 73);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '雅安市', 69);
INSERT INTO `rpt_pc_count` VALUES ('贵州省', '未知', 10);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '聊城市', 463);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '阿坝藏族羌族自治州', 27);
INSERT INTO `rpt_pc_count` VALUES ('宁夏回族自治区', '中卫市', 18);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '宜昌市', 285);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '张家口市', 180);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '未知', 141);
INSERT INTO `rpt_pc_count` VALUES ('西藏自治区', '山南地区', 4);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '济南市', 1558);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '博尔塔拉蒙古自治州', 12);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '内江市', 1317);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '未知', 42);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '河源市', 120);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '阿克苏地区', 17);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '徐州市', 1658);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '大连市', 749);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '喀什地区', 19);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '北海市', 192);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '合肥市', 3105);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '达州市', 177);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '辽阳市', 688);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '营口市', 340);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '钦州市', 158);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '蚌埠市', 249);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '玉林市', 323);
INSERT INTO `rpt_pc_count` VALUES ('上海市', '上海市', 4095);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '赤峰市', 288);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '梅州市', 348);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '丽水市', 269);
INSERT INTO `rpt_pc_count` VALUES ('西藏自治区', '拉萨市', 67);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '大理白族自治州', 30);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '永州市', 252);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '烟台市', 822);
INSERT INTO `rpt_pc_count` VALUES ('未知', '未知', 780);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '包头市', 157);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '嘉峪关市', 5);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '呼伦贝尔市', 244);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '驻马店市', 227);
INSERT INTO `rpt_pc_count` VALUES ('青海省', '海北藏族自治州', 2);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '佳木斯市', 420);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '芜湖市', 238);
INSERT INTO `rpt_pc_count` VALUES ('吉林省', '长春市', 1203);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '张掖市', 118);
INSERT INTO `rpt_pc_count` VALUES ('吉林省', '辽源市', 269);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '唐山市', 1449);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '东莞市', 969);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '鸡西市', 275);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '镇江市', 361);
INSERT INTO `rpt_pc_count` VALUES ('贵州省', '黔西南布依族苗族自治未知', 49);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '庆阳市', 60);
INSERT INTO `rpt_pc_count` VALUES ('香港特别行政区', '香港特别行政区', 121);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '濮阳市', 282);
INSERT INTO `rpt_pc_count` VALUES ('吉林省', '吉林市', 922);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '深圳市', 1497);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '泰安市', 418);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '凉山彝族自治州', 68);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '南宁市', 12938);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '成都市', 1277);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '宿州市', 270);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '巴彦淖尔市', 48);
INSERT INTO `rpt_pc_count` VALUES ('海南省', '三亚市', 11);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '盐城市', 705);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '江门市', 451);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '定西市', 49);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '沧州市', 965);
INSERT INTO `rpt_pc_count` VALUES ('贵州省', '遵义市', 178);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '乌兰察布市', 98);
INSERT INTO `rpt_pc_count` VALUES ('吉林省', '白城市', 84);
INSERT INTO `rpt_pc_count` VALUES ('青海省', '海西蒙古族藏族自治州', 4);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '西双版纳傣族自治州', 50);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '德宏傣族景颇族自治州', 39);
INSERT INTO `rpt_pc_count` VALUES ('福建省', '泉州市', 1008);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '荆州市', 214);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '佛山市', 885);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '淮安市', 628);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '池州市', 128);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '阿拉善盟', 14);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '汕尾市', 172);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '丹东市', 255);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '舟山市', 261);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '商洛市', 36);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '温州市', 1988);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '泸州市', 133);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '怀化市', 289);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '柳州市', 396);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '宿迁市', 517);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '珠海市', 385);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '来宾市', 74);
INSERT INTO `rpt_pc_count` VALUES ('贵州省', '黔东南苗族侗族自治州', 111);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '湘西土家族苗族自治州', 179);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '铁岭市', 288);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '莱芜市', 237);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '金华市', 1144);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '赣州市', 555);
INSERT INTO `rpt_pc_count` VALUES ('福建省', '龙岩市', 437);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '亳州市', 240);
INSERT INTO `rpt_pc_count` VALUES ('西藏自治区', '未知', 33);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '兰州市', 393);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '兴安盟', 44);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '揭阳市', 256);
INSERT INTO `rpt_pc_count` VALUES ('吉林省', '通化市', 207);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '宜宾市', 240);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '贺州市', 164);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '锡林郭勒盟', 55);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '大兴安岭地区', 49);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '常州市', 950);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '六安市', 251);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '潮州市', 75);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '锦州市', 180);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '沈阳市', 1772);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '萍乡市', 246);
INSERT INTO `rpt_pc_count` VALUES ('宁夏回族自治区', '未知', 1);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '南昌市', 2170);
INSERT INTO `rpt_pc_count` VALUES ('宁夏回族自治区', '固原市', 15);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '吉安市', 250);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '齐齐哈尔市', 205);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '南京市', 2234);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '淮北市', 389);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '百色市', 100);
INSERT INTO `rpt_pc_count` VALUES ('吉林省', '四平市', 253);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '七台河市', 102);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '贵港市', 190);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '德州市', 499);
INSERT INTO `rpt_pc_count` VALUES ('重庆市', '重庆市', 2966);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '周口市', 435);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '临沂市', 1148);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '茂名市', 198);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '开封市', 235);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '云浮市', 71);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '保定市', 979);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '滁州市', 247);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '梧州市', 198);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '马鞍山市', 278);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '咸阳市', 319);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '朝阳市', 134);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '榆林市', 165);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '伊春市', 38);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '武汉市', 3087);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '十堰市', 255);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '汕头市', 399);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '东营市', 402);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '普洱市', 105);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '娄底市', 278);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '鞍山市', 267);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '荆门市', 87);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '阳泉市', 320);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '杭州市', 3877);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '阜新市', 381);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '绥化市', 510);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '西安市', 2794);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '临沧市', 12);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '迪庆藏族自治州', 3);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '平凉市', 12);
INSERT INTO `rpt_pc_count` VALUES ('青海省', '未知', 14);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '牡丹江市', 408);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '长治市', 364);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '未知', 31);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '克孜勒苏柯尔克孜自治未知', 5);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '未知', 743);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '甘孜藏族自治州', 240);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '临夏回族自治州', 13);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '上饶市', 662);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '惠州市', 515);
INSERT INTO `rpt_pc_count` VALUES ('福建省', '宁德市', 270);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '克拉玛依市', 21);
INSERT INTO `rpt_pc_count` VALUES ('福建省', '福州市', 1412);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '许昌市', 401);
INSERT INTO `rpt_pc_count` VALUES ('海南省', '未知', 107);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '葫芦岛市', 252);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '信阳市', 611);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '漯河市', 138);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '安庆市', 298);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '未知', 48);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '金昌市', 10);
INSERT INTO `rpt_pc_count` VALUES ('台湾省', '未知', 1);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '南充市', 332);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '昆明市', 613);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '运城市', 247);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '德阳市', 190);
INSERT INTO `rpt_pc_count` VALUES ('辽宁省', '盘锦市', 103);
INSERT INTO `rpt_pc_count` VALUES ('福建省', '三明市', 245);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '枣庄市', 642);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '昌吉回族自治州', 46);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '桂林市', 396);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '阿勒泰地区', 11);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '宁波市', 1971);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '青岛市', 2272);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '衡水市', 543);
INSERT INTO `rpt_pc_count` VALUES ('吉林省', '白山市', 51);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '长沙市', 10431);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '郑州市', 2062);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '张家界市', 69);
INSERT INTO `rpt_pc_count` VALUES ('贵州省', '黔南布依族苗族自治州', 97);
INSERT INTO `rpt_pc_count` VALUES ('福建省', '漳州市', 599);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '广安市', 184);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '未知', 65);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '黄石市', 126);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '铜川市', 36);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '黑河市', 124);
INSERT INTO `rpt_pc_count` VALUES ('青海省', '果洛藏族自治州', 2);
INSERT INTO `rpt_pc_count` VALUES ('广西壮族自治区', '崇左市', 114);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '吕梁市', 70);
INSERT INTO `rpt_pc_count` VALUES ('福建省', '南平市', 251);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '哈尔滨市', 1680);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '岳阳市', 795);
INSERT INTO `rpt_pc_count` VALUES ('西藏自治区', '昌都地区', 1);
INSERT INTO `rpt_pc_count` VALUES ('青海省', '西宁市', 179);
INSERT INTO `rpt_pc_count` VALUES ('江苏省', '连云港市', 623);
INSERT INTO `rpt_pc_count` VALUES ('福建省', '莆田市', 271);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '甘南藏族自治州', 3);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '呼和浩特市', 399);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '鄂州市', 49);
INSERT INTO `rpt_pc_count` VALUES ('青海省', '海南藏族自治州', 6);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '邯郸市', 609);
INSERT INTO `rpt_pc_count` VALUES ('北京市', '北京市', 4962);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '渭南市', 250);
INSERT INTO `rpt_pc_count` VALUES ('黑龙江省', '未知', 2);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '太原市', 683);
INSERT INTO `rpt_pc_count` VALUES ('吉林省', '松原市', 312);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '平顶山市', 254);
INSERT INTO `rpt_pc_count` VALUES ('河南省', '未知', 24);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '晋中市', 426);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '未知', 3);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '文山壮族苗族自治州', 41);
INSERT INTO `rpt_pc_count` VALUES ('湖南省', '衡阳市', 488);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '乐山市', 166);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '自贡市', 307);
INSERT INTO `rpt_pc_count` VALUES ('四川省', '攀枝花市', 26);
INSERT INTO `rpt_pc_count` VALUES ('安徽省', '黄山市', 177);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '宝鸡市', 295);
INSERT INTO `rpt_pc_count` VALUES ('河北省', '承德市', 236);
INSERT INTO `rpt_pc_count` VALUES ('甘肃省', '天水市', 57);
INSERT INTO `rpt_pc_count` VALUES ('内蒙古自治区', '未知', 15);
INSERT INTO `rpt_pc_count` VALUES ('广东省', '中山市', 402);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '未知', 101);
INSERT INTO `rpt_pc_count` VALUES ('湖北省', '未知', 115);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '晋城市', 142);
INSERT INTO `rpt_pc_count` VALUES ('海南省', '海口市', 346);
INSERT INTO `rpt_pc_count` VALUES ('云南省', '昭通市', 72);
INSERT INTO `rpt_pc_count` VALUES ('陕西省', '安康市', 99);
INSERT INTO `rpt_pc_count` VALUES ('浙江省', '湖州市', 644);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '威海市', 531);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '伊犁哈萨克自治州', 35);
INSERT INTO `rpt_pc_count` VALUES ('山西省', '朔州市', 52);
INSERT INTO `rpt_pc_count` VALUES ('山东省', '淄博市', 406);
INSERT INTO `rpt_pc_count` VALUES ('江西省', '新余市', 82);
INSERT INTO `rpt_pc_count` VALUES ('新疆维吾尔自治区', '哈密地区', 32);

SET FOREIGN_KEY_CHECKS = 1;
